### ISSUE TITLE
Feature request: Change height of window

### ISSUE THREAD

**Issue by delebash** [sedabull/quantum-shell#10]
It would be nice to be able to change the height of the window by resize handles, if not that then having a setting where you can specify default height would help.

Thanks

**Comment by hoosierhobbyist** [comment]
this should be doable, I'll look into it as soon as I'm able

**Comment by delebash** [comment]
Great, thanks

**Comment by hoosierhobbyist** [comment]
This is closed as of version 0.5.0. Resizing Panels is not a simple thing, so I've included two options to set the maxHeight and minHeight properties of the output div.

**Comment by delebash** [comment]
thanks
