### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by opticyclic** [sedabull/quantum-shell#14]
Using Windows 7, Atom 0.204, Quantum Shell 0.6.1

C:\Users\opticyclic.atom\packages\quantum-shell\lib\quantum-shell-model.coffee:192
Hide Stack Trace
TypeError: undefined is not a function
  at QuantumShellModel.promptString (C:\Users\opticyclic.atom\packages\quantum-shell\lib\quantum-shell-model.coffee:192:42)
  at C:\Users\opticyclic.atom\packages\quantum-shell\lib\quantum-shell-controller.coffee:191:

**Comment by hoosierhobbyist** [comment]
this should be fixed in version 0.6.2, but feel free to reopen if the problem continues and let me know if you have any other problems :smiley:
