### ISSUE TITLE
Scrolling problem

### ISSUE THREAD

**Issue by jeroldhaas** [sedabull/quantum-shell#19]
The thing just grows and grows and grows in vertical size, and there's no way to scroll or fix the height of the terminal.

I usually run one or two commands, then use `cls` or `clear` (or destroy the shell session)  to actually see the edited document in the editor.

Can the shell's textbox be styled for scrollable content, and fix the size of the shell, or make it resizable? That would be tops!

**Comment by hoosierhobbyist** [comment]
There is a setting under `Settings>Packages>quantum-shell` for the max and min heights of the terminal panel. Could you try playing with those a little bit and let me know how it goes? If that doesn't work we'll have to do a little more digging :smiley:

**Comment by jeroldhaas** [comment]
Setting the max height to 400, along with the buffer line size, seems
to do the trick, however it seems to be ignoring the defaults (for
when no values are entered). Perhaps that's where the issue should be
directed?

On 22/08/2015, Seth David Bullock notifications@github.com wrote:

> There is a setting under `Settings>Packages>quantum-shell` for the max and
> min heights of the terminal panel. Could you try playing with those a little
> bit and let me know how it goes? If that doesn't work we'll have to do a
> little more digging :smiley:
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sedabull/quantum-shell/issues/19#issuecomment-133764638

## 

Cheers,
Jerold Haas

_Software Developer_
ASP.NET
ASP.NET MVC
C#, F#, .NET
PHP 4/5
JavaScript (jQuery, Mootools)
Flash / Flex 3 & 4 / ActionScript 2 & 3
MSSQL, MySQL, PostgreSQL
XHTML 1.0, HTML5, CSS2, CSS3

http://www.twitter.com/jeroldhaas
http://www.linkedin.com/in/jchaas
http://jhaas.emurse.com/

**Comment by hoosierhobbyist** [comment]
Yes, I would have to agree. Ignored defaults would be an issue with Atom. Is there a greyed out default value displayed in the input box before you type anything? And if so, what is it? I did a really quick search, and there don't seem to be any similar issues open with Atom right now.

**Comment by jeroldhaas** [comment]
Yes. 400 px for height, and 200 lines for backlogged lines.

On 22/08/2015, Seth David Bullock notifications@github.com wrote:

> Yes, I would have to agree. Ignored defaults would be an issue with Atom. Is
> there a greyed out default value displayed in the input box before you type
> anything? And if so, what is it? I did a really quick search, and there
> don't seem to be any similar issues open with Atom right now.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sedabull/quantum-shell/issues/19#issuecomment-133767007

## 

Cheers,
Jerold Haas

_Software Developer_
ASP.NET
ASP.NET MVC
C#, F#, .NET
PHP 4/5
JavaScript (jQuery, Mootools)
Flash / Flex 3 & 4 / ActionScript 2 & 3
MSSQL, MySQL, PostgreSQL
XHTML 1.0, HTML5, CSS2, CSS3

http://www.twitter.com/jeroldhaas
http://www.linkedin.com/in/jchaas
http://jhaas.emurse.com/

**Comment by hoosierhobbyist** [comment]
I'm going to apologize now if this sounds like a stupid question...but are you sure you're using `quantum-shell`, and if you are is it version `0.6.2`? My current default for maximum height is `250px` and I don't have a backlogged lines option.

**Comment by jeroldhaas** [comment]
My apologies.

The backlogged lines option is called "maximum history," and, my
mistake, it's 100 lines (I was trying to recall from memory). Max
height is at 250. The module "quantum-shell" is at version 0.6.2.

Nevertheless, it wouldn't limit height or scroll without those options entered.

On 22/08/2015, Seth David Bullock notifications@github.com wrote:

> I'm going to apologize now if this sounds like a stupid question...but are
> you sure you're using `quantum-shell`, and if you are is it version `0.6.2`?
> My current default for maximum height is `250px` and I don't have a
> backlogged lines option.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sedabull/quantum-shell/issues/19#issuecomment-133767124

## 

Cheers,
Jerold Haas

_Software Developer_
ASP.NET
ASP.NET MVC
C#, F#, .NET
PHP 4/5
JavaScript (jQuery, Mootools)
Flash / Flex 3 & 4 / ActionScript 2 & 3
MSSQL, MySQL, PostgreSQL
XHTML 1.0, HTML5, CSS2, CSS3

http://www.twitter.com/jeroldhaas
http://www.linkedin.com/in/jchaas
http://jhaas.emurse.com/

**Comment by hoosierhobbyist** [comment]
That's quite alright! Just a minor miscommunication. The maximum history option actually determines how many commands to record so they can be easily recalled using the up and down arrow keys. As far as you're issue is concerned though, it will require further investigation. Could you tell me what OS you're on, as well as your version of Atom? I won't have time to look into it tonight, but as soon as I can I'll see what I can do.

**Comment by jeroldhaas** [comment]
Aah, yes, that's a different animal altogether, isn't it? :smile:

I'm running Atom 1.0.7 on Windows 10. If you need add'l info (packages
installed) I'll happily provide it when/if needed.

On 22/08/2015, Seth David Bullock notifications@github.com wrote:

> That's quite alright! Just a minor miscommunication. The maximum history
> option actually determines how many commands to record so they can be easily
> recalled using the up and down arrow keys. As far as you're issue is
> concerned though, it will require further investigation. Could you tell me
> what OS you're on, as well as your version of Atom? I won't have time to
> look into it tonight, but as soon as I can I'll see what I can do.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sedabull/quantum-shell/issues/19#issuecomment-133767775

## 

Cheers,
Jerold Haas

_Software Developer_
ASP.NET
ASP.NET MVC
C#, F#, .NET
PHP 4/5
JavaScript (jQuery, Mootools)
Flash / Flex 3 & 4 / ActionScript 2 & 3
MSSQL, MySQL, PostgreSQL
XHTML 1.0, HTML5, CSS2, CSS3

http://www.twitter.com/jeroldhaas
http://www.linkedin.com/in/jchaas
http://jhaas.emurse.com/

**Comment by hoosierhobbyist** [comment]
If you wouldn't mind experimenting with packages other than `quantum-shell` to see if this is an isolated issue, that would be awesome :smile:

**Comment by jeroldhaas** [comment]
I've been experimenting with a lot of packages lately, and many of
them have text entry fields (linters using executables that require
path to executable, otherwise using system PATH), and I hadn't
encountered any text boxes being ignored in the past.

I'll keep mucking about with the ones I have and see if any others
might ignore the textbox. A mate of mine works on atom-fsharp and he's
using a textbox with default value also. I'll ask him if he'd
encountered any issues.

Thanks for looking into this, the awesome shell, and your help!

On 22/08/2015, Seth David Bullock notifications@github.com wrote:

> If you wouldn't mind experimenting with packages other than `quantum-shell`
> to see if this is an isolated issue, that would be awesome :smile:
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sedabull/quantum-shell/issues/19#issuecomment-133768145

## 

Cheers,
Jerold Haas

_Software Developer_
ASP.NET
ASP.NET MVC
C#, F#, .NET
PHP 4/5
JavaScript (jQuery, Mootools)
Flash / Flex 3 & 4 / ActionScript 2 & 3
MSSQL, MySQL, PostgreSQL
XHTML 1.0, HTML5, CSS2, CSS3

http://www.twitter.com/jeroldhaas
http://www.linkedin.com/in/jchaas
http://jhaas.emurse.com/

**Comment by hoosierhobbyist** [comment]
No problem! Thanks for using `quantum-shell` and helping to make it better!

**Comment by hoosierhobbyist** [comment]
Hello, I know it's been a while, but could you let me know if you're still having this issue and if you are could you pull up the debugging console `ctrl-shift-i` and type the command `atom.config.get('quantum-shell.maxHeight');` and let me know what the return value is?

Note: `quantum-shell` should be active when you do this.

**Comment by hoosierhobbyist** [comment]
Other Note: please remove the number you entered manually into the config settings.

**Comment by jeroldhaas** [comment]
Should I run update first?

**Comment by jeroldhaas** [comment]
After removing the number from the textbox field, the value returned is 250. Perhaps it was a one-off issue, then?

**Comment by hoosierhobbyist** [comment]
It could be, does the original issue still persist?

—

**Comment by jeroldhaas** [comment]
I've managed to reproduce the error again, however I'm not sure precisely the steps. I'll make a list of what I did:
- Removed all custom options, setting them to their default value, with quantum-shell open
- Opened new terminal in quantum-shell
- Closed old session, returning to new session
- Typed `ls` or `dir` enough times to cause expansion of the shell height

Attached is a screen-shot:
![image](https://cloud.githubusercontent.com/assets/835976/9816086/aa9797f6-5868-11e5-9626-dacd269f306d.png)

**Comment by jeroldhaas** [comment]
Note that if I continue typing `dir` or `ls` the top of the shell (as well as the bottom) goes out of sight:

![image](https://cloud.githubusercontent.com/assets/835976/9816124/ff2e05d4-5868-11e5-88ed-221a295ff76a.png)

**Comment by jeroldhaas** [comment]
Only custom options set are shell name and user name. Is there a possibility that `cmd.exe` is causing the extra expansion?

**Comment by hoosierhobbyist** [comment]
Honestly this is very strange and i have no idea whats causing it. Could you possibly test this on a different OS, preferably windows 8?

**Comment by jeroldhaas** [comment]
I'm sorry I have _no_ Windows 8 boxes at my current location or at home. :frowning:

**Comment by hoosierhobbyist** [comment]
Ok no problem! I'll see what i can do when i have some free time.

**Comment by hoosierhobbyist** [comment]
This issue should be resolved now, so please upgrade to version 0.7.0 and let me know if it works!

**Comment by jeroldhaas** [comment]
This is confirmed fixed. _Thanks_ ! :smiley:

**Comment by hoosierhobbyist** [comment]
Any time! Let me know if you have any more issues :smile:
