### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by cryptodyno** [sedabull/quantum-shell#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.2
**Thrown From**: [quantum-shell](https://github.com/sedabull/quantum-shell) package, v0.3.3
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /Users/kbaylog/.atom/packages/quantum-shell/lib/quantum-shell-model.coffee:162

TypeError: Cannot read property 'length' of null
  at QuantumShellModel.process (/Users/kbaylog/.atom/packages/quantum-shell/lib/quantum-shell-model.coffee:162:9)
  at HTMLButtonElement.submit.onclick (/Users/kbaylog/.atom/packages/quantum-shell/lib/quantum-shell-view.coffee:49:15)
  at HTMLInputElement.<anonymous> (/Users/kbaylog/.atom/packages/quantum-shell/lib/quantum-shell-model.coffee:89:61)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/kbaylog/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Users/kbaylog/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/kbaylog/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/kbaylog/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/kbaylog/Downloads/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)

```
### Commands

```
     -6:36.9 core:cancel (atom-text-editor.editor.mini)
     -6:35.8 core:select-all (atom-text-editor.editor.mini)
     -6:35.3 core:confirm (atom-text-editor.editor.mini)
     -3:46.6 editor:newline (atom-text-editor.editor)
     -3:44.1 core:undo (atom-text-editor.editor)
     -3:40.8 terminal-panel:new (atom-text-editor.editor)
     -3:32.5 terminal-panel:toggle (atom-text-editor.editor)
     -2:49.0 core:confirm (atom-text-editor.editor.mini)
     -2:09.2 core:select-all (atom-text-editor.editor.mini)
     -2:08.5 core:confirm (atom-text-editor.editor.mini)
     -2:07.1 core:select-all (atom-text-editor.editor.mini)
     -2:05.6 core:confirm (atom-text-editor.editor.mini)
     -0:49.5 core:select-all (atom-text-editor.editor.mini)
     -0:48.2 core:confirm (atom-text-editor.editor.mini)
     -0:06.8 quantum-shell:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
  3x -0:01.9 quantum-shell:submit (input#quantum-shell-input)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.6.1
quantum-shell, v0.3.3
remote-edit, v1.6.4

# Dev
No dev packages
```

**Comment by hoosierhobbyist** [comment]
Can I ask, did this happen when simply pressing enter, without typing anything?

**Comment by cryptodyno** [comment]
It’s a possibility, but I’m not sure what happened exactly. My purpose for using quantum-shell was to open an ssh to watch node.js run in the same window as the development. I didn’t realize that it’s not possible to run ssh from within the shell. This wasn’t a result of attempting to run ssh, however. It happened prior to that.

Warm regards,

Kristopher Baylog, COO | Matricom
This transmission is confidential and intended solely for the person or organization to whom it is addressed. It may contain privileged and confidential information. If you are not the intended recipient you should not copy, distribute or take any action in reliance on it. If you have received this transmission in error, please immediately notify the sender at the e-mail address above and delete this email.

**Comment by hoosierhobbyist** [comment]
Ok, I believe that probably was it because that's how I was able to reproduce the issue at home. Thank you for the bug report! Also, I'm not sure if you're aware of this, but you're emails are publically visible on github at http://github.com/sedabull/quantum-shell/issues/5. If that's an issue, as you're email signature would seem to imply, you're more than welcome to come here and delete them. I have all the information I need to push out a patch in the next day or two.

**Comment by cryptodyno** [comment]
Thanks for the info, it's no problem :) looking forward to the patch. Great
plugin by the way!

**Comment by hoosierhobbyist** [comment]
Thank you! It's nice to hear that people are using it out in the wild :smile:
