### ISSUE TITLE
Feature Request: Tab Completion

### ISSUE THREAD

**Issue by hxegon** [sedabull/quantum-shell#7]
Would really appreciate proper (case-insensitive) tab completion, as it is an extremely useful feature in my opinion.

**Comment by hoosierhobbyist** [comment]
Could you point to an explicit example of what you mean? I apologize, but I'm not very familiar.

**Comment by hoosierhobbyist** [comment]
All right, I did a little research on [wikipedia](http://en.wikipedia.org/wiki/Command-line_completion), and I believe this is doable. Could you tell me:
- Is this definitely what you meant?
- If it is would you prefer the prompting completion or rotating completion?
- Do you want to take a crack at it or should I?

Personally I'm leaning towards rotating completion, as I believe it would be a little easier to implement, but if there's a compelling reason, I'd be willing to try prompting.

**Comment by hxegon** [comment]
Sorry about the late response, that is exactly what I mean. Thanks for the quick response!

**Comment by hoosierhobbyist** [comment]
Very well, I will do my best to make this a part of the next release. Although, that may be a few weeks, I am currently busy with several other things. Thank you for the suggestion :smile:

**Comment by hxegon** [comment]
Thanks for making this. looking forward to the next release.

**Comment by hoosierhobbyist** [comment]
@clebrun, I had some extra time tonight, so I decided to go ahead and tackle this. It was actually surprisingly easy to implement, which has me a little-bit worried :worried:. Despite that however, I have published a new  version I would greatly appreciate any feedback you might have.

**Comment by hxegon** [comment]
alright, I'll check it out and get back to you. Thanks for the quick
implementation!

**Comment by hoosierhobbyist** [comment]
Update: I discovered a bug that would cause the file name completion to act a little funky, but short story short: I fixed it and released a patch. Other than that though, I believe this feature is behaving as expected, so I am going to go ahead and close this issue. Please let me know if you discover any bugs or have any other feature requests. I truly appreciate you reaching out to me :smiley:
